name: test1

on:
  push:
    branches:
      - master

jobs:
  filesChanged:
    uses: ./.github/workflows/files_changed.yaml
    with:
      folder_path: .*
  merge-job:
    runs-on: ubuntu-latest
    needs: filesChanged
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Obtener archivos modificados
        id: get-modified-files
        run: |
          echo "${{ needs.filesChanged.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
          echo boolean_output=${{ needs.filesChanged.outputs.boolean_output }}

      - name: Ejecutar script Python
        run: python -u workflow.py $GITHUB_OUTPUT