name: test1

on:
  push:
    branches:
      - master

jobs:
  merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Obtener archivos modificados
        id: modified-files
        run: | 
          echo "files=$(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_OUTPUT
      
      - name: Echo variable
        id: echo-var
        run: |
          echo ${{ needs.filesChanged.outputs.all_changed_files }} 
          echo boolean_output=${{ needs.filesChanged.outputs.boolean_output }} 
          echo $GITHUB_OUTPUT

      - name: Ejecutar script Python
        run: python -u workflow.py $GITHUB_OUTPUT