name: test1

on:
  push:
    branches:
      - master

jobs:
  merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Obtener detalles del commit
        id: commit-details
        run: |
          echo "::set-output name=commit-author::$(git show -s --format='%an' ${{ github.sha }})"
          echo "::set-output name=commit-message::$(git show -s --format='%s' ${{ github.sha }})"

      - name: Obtener archivos modificados
        id: modified-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"

      - name: Ejecutar script Python
        run: python workflow.py ${{ steps.modified-files.outputs.files }}